PIN-3232 [BE] [Tenant Management] Salvare tipologia ente
pagopa/interop-be-tenant-management pull request #57
Opened 2023-04-13 11:58 UTC by nttdata-rtorsoli

2023-04-14 06:52 UTC, beetlecrunch commented on models/src/main/scala/it/pagopa/interop/tenantmanagement/model/persistence/JsonFormats.scala
> +        case JsString("GSP")     => PersistentTenantKind.Gsp
May I suggest using upper case for every character in acronyms?

2023-04-14 06:53 UTC, beetlecrunch commented on models/src/main/scala/it/pagopa/interop/tenantmanagement/model/tenant/PersistentTenantKind.scala
> +  case object Gsp     extends PersistentTenantKind
May I suggest using upper case for every character in acronyms?

2023-04-14 06:54 UTC, beetlecrunch approved these changes

2023-04-14 13:00 UTC, galales requested changes

2023-04-14 13:00 UTC, galales commented on src/main/resources/interface-specification.yml
> +        kind:
`kind` must be mandatory in the seed

2023-04-14 13:00 UTC, galales commented on src/main/resources/interface-specification.yml
> +        kind:
same, `kind` must be mandatory in the seed

2023-04-17 08:43 UTC, TonioGela approved these changes

2023-04-26 07:19 UTC, galales approved these changes

2023-05-09 06:35 UTC, merged